services:
  - type: web
    name: DomWatch
    env: python
    buildCommand: bash render-build.sh # Use your custom build script
    startCommand: |
      export PATH="${PATH}:/opt/render/project/.render/chrome/opt/google/chrome:/opt/render/project/.render/chromedriver" && \
      gunicorn app:app
    envVars:
      - key: SENDER_EMAIL
        type: secret
        name: domwatch_sender_email_secret
      - key: SENDER_PASSWORD
        type: secret
        name: domwatch_sender_password_secret
      - key: SUPABASE_URL
        type: secret
        name: domwatch_supabase_url_secret
      - key: SUPABASE_KEY
        type: secret
        name: domwatch_supabase_key_secret
